export const GAME_CONFIG = {
  worldSize: 3600,
  districtSize: 1120,
  districtSpacing: 520,
  hoverFloor: 8,
  hoverCeiling: 220,
  mission: {
    baseFareMin: 62,
    baseFareMax: 126,
    distanceFareMultiplier: 0.04,
    timePenaltyPerSecond: 1.5,
    collisionPenalty: 12,
    pickupRadius: 12,
    dropoffRadius: 14,
    finalCreditsThreshold: 10000,
    specialFareThreshold: 350,
    specialFareMinSeconds: 15,
    specialFareMaxSeconds: 20,
    specialFareMinCredits: 300,
    specialFareMaxCredits: 500,
    fakePassengerThresholdCredits: 4500,
    fakePassengerMinRobberyCredits: 500,
    fakePassengerMaxRobberyCredits: 750,
  },
  energy: {
    maxEnergy: 100,
    baseDrainPerSecond: 0.14,
    motionDrainPerSecond: 0.22,
    boostDrainPerSecond: 0.5,
    stationRadius: 14,
    refuelSeconds: 5,
    depletedMovementScale: 0.4,
    emptyPassengerPenalty: 1000,
  },
  player: {
    maxForwardSpeed: 90,
    maxReverseSpeed: 24,
    acceleration: 82,
    braking: 110,
    drag: 1.9,
    turnSpeed: 2.6,
    verticalSpeed: 48,
    verticalAcceleration: 72,
    strafeSpeed: 22,
    strafeAcceleration: 42,
    collisionRadius: 4.2,
    boostDuration: 3,
    boostCooldown: 5,
    boostSpeedMultiplier: 2.15,
    boostAccelerationMultiplier: 1.6,
    boostCollisionPenaltyMultiplier: 2.4,
  },
  cityLimits: {
    turnAroundBuffer: 180,
    returnInset: 64,
  },
  camera: {
    followDistance: 18,
    height: 7,
    lookAhead: 14,
    damping: 5.2,
  },
  traffic: {
    obstacleCount: 56,
    ambientCount: 54,
  },
  rivals: {
    poolSize: 52,
    despawnDistance: 900,
    endgameCreditsThreshold: 10000,
    normalSpawnCooldownSeconds: 20,
    heat: {
      maxHeat: 10,
      timeGainPerSecond: 0.013,
      creditsGainFactor: 0.0028,
      fareCompletionGain: 0.38,
      perfectFareBonus: 0.18,
      speedPressureThreshold: 0.84,
      speedGainPerSecond: 0.075,
      collisionGain: 0.16,
      baseDecayPerSecond: 0.014,
      safeDecayPerSecond: 0.06,
    },
    spawn: {
      minSpawnDistance: 180,
      maxSpawnDistance: 340,
      sideSpawnDistance: 90,
      sideSpawnVariance: 120,
      lowHeatBands: [16, 28, 42],
      midHeatBands: [20, 40, 68, 96],
      highHeatBands: [24, 56, 92, 126, 154],
    },
    agent: {
      radius: 4.3,
      baseSpeed: 74,
      baseForce: 28,
      collisionPenalty: 18,
      collisionStrength: 0.42,
      avoidanceDistance: 26,
      separationDistance: 18,
    },
  },
  emp: {
    spawnIntervalSeconds: 90,
    pickupRadius: 14,
    maxCharges: 5,
    maxTargetsPerBlast: 10,
    blastRadius: 360,
    respawnDelayAfterUse: 5,
  },
  superBoost: {
    spawnIntervalMinSeconds: 150,
    spawnIntervalMaxSeconds: 240,
    pickupRadius: 14,
    maxCharges: 1,
    duration: 60,
  },
  lightning: {
    startCredits: 2000,
    pauseCredits: 4000,
    navigatorOfflineCredits: 6000,
    resumeCredits: 7000,
    minHeight: 108,
    openSkyHeight: 142,
    nearbyBuildingRadius: 56,
    roofClearance: 8,
    warningSeconds: 1.05,
    cooldownMinSeconds: 4.5,
    cooldownMaxSeconds: 9,
    warningSparkIntervalSeconds: 0.16,
    passengerPenalty: 100,
    flashSeconds: 0.42,
    flashIntensity: 7.5,
  },
};
