export const GAME_CONFIG = {
  worldSize: 3600,
  districtSize: 1120,
  districtSpacing: 520,
  hoverFloor: 8,
  hoverCeiling: 180,
  mission: {
    baseFareMin: 55,
    baseFareMax: 115,
    distanceFareMultiplier: 0.04,
    timePenaltyPerSecond: 2.4,
    collisionPenalty: 12,
    pickupRadius: 12,
    dropoffRadius: 14,
  },
  energy: {
    maxEnergy: 100,
    baseDrainPerSecond: 0.14,
    motionDrainPerSecond: 0.22,
    boostDrainPerSecond: 0.5,
    stationRadius: 14,
    refuelSeconds: 5,
    depletedMovementScale: 0.4,
    emptyPassengerPenalty: 1000,
  },
  player: {
    maxForwardSpeed: 90,
    maxReverseSpeed: 24,
    acceleration: 82,
    braking: 110,
    drag: 1.9,
    turnSpeed: 2.6,
    verticalSpeed: 48,
    verticalAcceleration: 72,
    strafeSpeed: 22,
    strafeAcceleration: 42,
    collisionRadius: 4.2,
    boostDuration: 3,
    boostCooldown: 5,
    boostSpeedMultiplier: 2.15,
    boostAccelerationMultiplier: 1.6,
    boostCollisionPenaltyMultiplier: 2.4,
  },
  camera: {
    followDistance: 18,
    height: 7,
    lookAhead: 14,
    damping: 5.2,
  },
  traffic: {
    obstacleCount: 48,
    ambientCount: 36,
  },
  rivals: {
    poolSize: 20,
    despawnDistance: 900,
    heat: {
      maxHeat: 10,
      timeGainPerSecond: 0.014,
      creditsGainFactor: 0.0035,
      fareCompletionGain: 0.5,
      perfectFareBonus: 0.35,
      speedPressureThreshold: 0.78,
      speedGainPerSecond: 0.12,
      collisionGain: 0.28,
      baseDecayPerSecond: 0.01,
      safeDecayPerSecond: 0.05,
    },
    spawn: {
      minSpawnDistance: 180,
      maxSpawnDistance: 340,
      sideSpawnDistance: 90,
      sideSpawnVariance: 120,
      lowHeatBands: [16, 28, 42],
      midHeatBands: [20, 40, 68, 96],
      highHeatBands: [24, 56, 92, 126, 154],
    },
    agent: {
      radius: 4.3,
      baseSpeed: 74,
      baseForce: 28,
      collisionPenalty: 18,
      collisionStrength: 0.42,
      avoidanceDistance: 26,
      separationDistance: 18,
    },
  },
};
